version: '3.8'

services:
  web:
    build: ./fims-app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./fims-app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=fims
      - POSTGRES_PASSWORD=fims
      - POSTGRES_DB=fims_dev

volumes:
  postgres_data:
