# Generated by Django 4.0.7 on 2022-10-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_name',
        ),
    ]
